export const REQUEST_LIST_DATA = 'REQUEST_LIST_DATA';
export const REQUEST_RESOURCES = 'REQUEST_RESOURCES';
export const RECEIVE_RESOURCES = 'RECEIVE_RESOURCES';
export const INVALIDATE_RESOURCES = 'INVALIDATE_RESOURCES';
export const ADD_NEW_RESOURCE_REQUEST = 'ADD_NEW_RESOURCE_REQUEST';
export const ADD_NEW_SKILL = 'ADD_NEW_SKILL';
